apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy34
  labels:
    app: autodeploy34
  namespace: namespace-workflow-1700053003353
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy34
  template:
    metadata:
      labels:
        app: autodeploy34
    spec:
      containers:
        - name: autodeploy34
          image: acrworkflow1700053003353.azurecr.io/image-workflow-1700053003353:latest
          ports:
            - containerPort: 5000